---
- name: ensure collectd.conf
  template:
    src: "collectd.conf.j2"
    dest: "{{ collectd_conf_file }}"
    owner: "{{ collectd_user }}"
    group: "{{ collectd_group }}"
    mode: 0644
    validate: "collectd -t"
  register: collectd_conf
  become: true

- name: ensure collectd plugins
  template:
    src: "collectd.plugin.j2"
    dest: "{{ collectd_conf_include_dir }}/{{ item.file_name | default(item.name) }}.conf"
    owner: "{{ collectd_user }}"
    group: "{{ collectd_group }}"
    mode: 0644
    validate: "collectd -t"
  loop: "{{ collectd_plugins }}"
  register: collectd_plugins_conf
  become: true
